name: spigot-plugin-bad-apple
version: '0.1.0-alpha4'
main: qwq.zyu.spigotPluginBadApple.SpigotPluginBadApple
api-version: '1.21'

commands:
  play_bad_apple:
    description: 播放bad_apple
    usage: /play_bad_apple [模式] (默认模式: block)
  debug_text_display_chess:
    description: 创建3x3文本展示实体棋盘用于调试
    usage: /debug_text_display_chess
  clear_chess_debug:
    description: 清除调试创建的棋盘实体
    usage: /clear_chess_debug